# Generated by Django 5.0.7 on 2024-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discount', models.FloatField(default=0)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(null=True, upload_to='')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('admin_username', models.CharField(max_length=100)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('lats_update_admin_username', models.CharField(max_length=100)),
                ('attributes', models.ManyToManyField(to='api.attribute')),
                ('images', models.ManyToManyField(to='api.image')),
            ],
        ),
    ]
