# Generated by Django 5.0.7 on 2024-09-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_attributes',
            field=models.ManyToManyField(related_name='product_default_attributes', to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(related_name='product_attributes', to='api.attribute'),
        ),
    ]
