# Generated by Django 5.0.7 on 2024-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_default_attributes_alter_product_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_attributes',
            field=models.ManyToManyField(to='api.defaultattribute'),
        ),
    ]
