# Generated by Django 5.0.7 on 2024-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('decription', models.TextField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
